"""initial hosted product schema

Revision ID: e43f5e49699d
Revises:
Create Date: 2026-08-02 17:14:07.792141
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e43f5e49699d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_versions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('prompt_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_name', 'version', 'content_hash', name='uq_prompt_name_version_hash')
    )
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_versions_prompt_name'), ['prompt_name'], unique=False)

    op.create_table('workflow_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=True),
    sa.Column('error_category', sa.String(length=100), nullable=True),
    sa.Column('safe_error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_workflow_job_idempotency_key')
    )
    with op.batch_alter_table('workflow_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_jobs_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_jobs_input_hash'), ['input_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_jobs_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_jobs_status'), ['status'], unique=False)

    op.create_table('iterations',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('audience', sa.Text(), nullable=False),
    sa.Column('raw_input_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('iterations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_iterations_project_id'), ['project_id'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('iteration_id', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('revision_performed', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('planner_prompt_version_id', sa.String(length=255), nullable=False),
    sa.Column('writer_prompt_version_id', sa.String(length=255), nullable=False),
    sa.Column('evaluator_prompt_version_id', sa.String(length=255), nullable=False),
    sa.Column('reviser_prompt_version_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['evaluator_prompt_version_id'], ['prompt_versions.id'], ),
    sa.ForeignKeyConstraint(['iteration_id'], ['iterations.id'], ),
    sa.ForeignKeyConstraint(['planner_prompt_version_id'], ['prompt_versions.id'], ),
    sa.ForeignKeyConstraint(['reviser_prompt_version_id'], ['prompt_versions.id'], ),
    sa.ForeignKeyConstraint(['writer_prompt_version_id'], ['prompt_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_iteration_id'), ['iteration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_status'), ['status'], unique=False)

    op.create_table('artifacts',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=False),
    sa.Column('artifact_type', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'artifact_type', name='uq_artifact_run_type')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_run_id'), ['run_id'], unique=False)

    op.create_table('evaluations',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=False),
    sa.Column('technical_accuracy', sa.Integer(), nullable=False),
    sa.Column('specificity', sa.Integer(), nullable=False),
    sa.Column('readability', sa.Integer(), nullable=False),
    sa.Column('reader_value', sa.Integer(), nullable=False),
    sa.Column('evidence_coverage', sa.Integer(), nullable=False),
    sa.Column('feedback_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluations_run_id'), ['run_id'], unique=True)

    op.create_table('run_observations',
    sa.Column('run_id', sa.String(length=255), nullable=False),
    sa.Column('iteration_id', sa.String(length=255), nullable=True),
    sa.Column('output_type', sa.String(length=100), nullable=False),
    sa.Column('pipeline_status', sa.String(length=30), nullable=False),
    sa.Column('observability_status', sa.String(length=30), nullable=False),
    sa.Column('reproducibility_status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('model_digest', sa.String(length=255), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('prompt_versions_json', sa.JSON(), nullable=False),
    sa.Column('prompt_file_hashes_json', sa.JSON(), nullable=False),
    sa.Column('configuration_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('git_commit', sa.String(length=64), nullable=True),
    sa.Column('git_branch', sa.String(length=255), nullable=True),
    sa.Column('working_tree_dirty', sa.Boolean(), nullable=True),
    sa.Column('llm_call_count', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('slowest_step', sa.String(length=100), nullable=True),
    sa.Column('highest_token_step', sa.String(length=100), nullable=True),
    sa.Column('revision_performed', sa.Boolean(), nullable=False),
    sa.Column('revision_decision_json', sa.JSON(), nullable=True),
    sa.Column('revision_output_changed', sa.Boolean(), nullable=True),
    sa.Column('revision_improvement_status', sa.String(length=30), nullable=False),
    sa.Column('reproducibility_json', sa.JSON(), nullable=False),
    sa.Column('observability_issues_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    with op.batch_alter_table('run_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_observations_observability_status'), ['observability_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_observations_pipeline_status'), ['pipeline_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_observations_reproducibility_status'), ['reproducibility_status'], unique=False)

    op.create_table('step_observations',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('skip_reason', sa.String(length=100), nullable=True),
    sa.Column('timing_mode', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'step_name', name='uq_step_observation_run_name')
    )
    with op.batch_alter_table('step_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_step_observations_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_step_observations_status'), ['status'], unique=False)

    op.create_table('artifact_dependencies',
    sa.Column('id', sa.String(length=500), nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=False),
    sa.Column('artifact_id', sa.String(length=255), nullable=False),
    sa.Column('producer_step_name', sa.String(length=100), nullable=False),
    sa.Column('source_artifact_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['artifacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifact_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_dependencies_artifact_id'), ['artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_dependencies_run_id'), ['run_id'], unique=False)

    op.create_table('llm_call_observations',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=False),
    sa.Column('step_id', sa.String(length=255), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('model_digest', sa.String(length=255), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('prompt_file_hash', sa.String(length=64), nullable=True),
    sa.Column('rendered_prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('token_usage_status', sa.String(length=30), nullable=False),
    sa.Column('token_usage_source', sa.String(length=100), nullable=False),
    sa.Column('finish_reason', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('error_category', sa.String(length=50), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['step_observations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_call_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_call_observations_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_call_observations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_call_observations_step_name'), ['step_name'], unique=False)

    op.create_table('publish_receipts',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('attempt_id', sa.String(length=255), nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=False),
    sa.Column('artifact_id', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('account_reference', sa.String(length=128), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('external_post_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('api_endpoint', sa.Text(), nullable=False),
    sa.Column('api_version', sa.String(length=20), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error_category', sa.String(length=100), nullable=True),
    sa.Column('safe_error_message', sa.Text(), nullable=True),
    sa.Column('duplicate_of_receipt_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['duplicate_of_receipt_id'], ['publish_receipts.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', name='uq_publish_receipt_attempt')
    )
    with op.batch_alter_table('publish_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publish_receipts_account_reference'), ['account_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_publish_receipts_artifact_id'), ['artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publish_receipts_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publish_receipts_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_publish_receipts_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_publish_receipts_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publish_receipts_status'), ['status'], unique=False)

    op.create_table('error_observations',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=True),
    sa.Column('llm_call_id', sa.String(length=255), nullable=True),
    sa.Column('error_category', sa.String(length=50), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=False),
    sa.Column('exception_type', sa.String(length=255), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.Column('sanitized_message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['llm_call_id'], ['llm_call_observations.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('error_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_error_observations_error_category'), ['error_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_observations_error_code'), ['error_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_observations_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('error_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_error_observations_run_id'))
        batch_op.drop_index(batch_op.f('ix_error_observations_error_code'))
        batch_op.drop_index(batch_op.f('ix_error_observations_error_category'))

    op.drop_table('error_observations')
    with op.batch_alter_table('publish_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publish_receipts_status'))
        batch_op.drop_index(batch_op.f('ix_publish_receipts_run_id'))
        batch_op.drop_index(batch_op.f('ix_publish_receipts_platform'))
        batch_op.drop_index(batch_op.f('ix_publish_receipts_content_hash'))
        batch_op.drop_index(batch_op.f('ix_publish_receipts_attempt_id'))
        batch_op.drop_index(batch_op.f('ix_publish_receipts_artifact_id'))
        batch_op.drop_index(batch_op.f('ix_publish_receipts_account_reference'))

    op.drop_table('publish_receipts')
    with op.batch_alter_table('llm_call_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_call_observations_step_name'))
        batch_op.drop_index(batch_op.f('ix_llm_call_observations_status'))
        batch_op.drop_index(batch_op.f('ix_llm_call_observations_run_id'))

    op.drop_table('llm_call_observations')
    with op.batch_alter_table('artifact_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_dependencies_run_id'))
        batch_op.drop_index(batch_op.f('ix_artifact_dependencies_artifact_id'))

    op.drop_table('artifact_dependencies')
    with op.batch_alter_table('step_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_step_observations_status'))
        batch_op.drop_index(batch_op.f('ix_step_observations_run_id'))

    op.drop_table('step_observations')
    with op.batch_alter_table('run_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_observations_reproducibility_status'))
        batch_op.drop_index(batch_op.f('ix_run_observations_pipeline_status'))
        batch_op.drop_index(batch_op.f('ix_run_observations_observability_status'))

    op.drop_table('run_observations')
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluations_run_id'))

    op.drop_table('evaluations')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_run_id'))

    op.drop_table('artifacts')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_status'))
        batch_op.drop_index(batch_op.f('ix_runs_iteration_id'))

    op.drop_table('runs')
    with op.batch_alter_table('iterations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_iterations_project_id'))

    op.drop_table('iterations')
    with op.batch_alter_table('workflow_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_workflow_jobs_run_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_jobs_input_hash'))
        batch_op.drop_index(batch_op.f('ix_workflow_jobs_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_workflow_jobs_created_at'))

    op.drop_table('workflow_jobs')
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_versions_prompt_name'))

    op.drop_table('prompt_versions')
    op.drop_table('projects')
    # ### end Alembic commands ###
